# Generated by Django 5.0.4 on 2026-04-13 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('client_score', models.IntegerField()),
                ('backend_score', models.IntegerField(blank=True, null=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('verdict', models.CharField(max_length=20)),
                ('flags', models.JSONField(default=list)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('google_safe_browsing', models.JSONField(blank=True, null=True)),
                ('redirect_chain', models.JSONField(blank=True, null=True)),
                ('ssl_valid', models.BooleanField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['user_id', '-scanned_at'], name='linkguard_l_user_id_d653b1_idx')],
            },
        ),
    ]
