# Generated by Django 5.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkguard", "0001_initial"),
    ]

    operations = [
        # Make client_score nullable (new scans don't require it)
        migrations.AlterField(
            model_name="linkscan",
            name="client_score",
            field=models.IntegerField(null=True, blank=True),
        ),
        # New component scores
        migrations.AddField(
            model_name="linkscan",
            name="url_score",
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="linkscan",
            name="domain_score",
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="linkscan",
            name="threat_score",
            field=models.IntegerField(null=True, blank=True),
        ),
        # Human-readable verdict label
        migrations.AddField(
            model_name="linkscan",
            name="status",
            field=models.CharField(max_length=20, default=""),
        ),
        # Reason strings (human-readable list)
        migrations.AddField(
            model_name="linkscan",
            name="reasons",
            field=models.JSONField(default=list),
        ),
        # AI tactics list
        migrations.AddField(
            model_name="linkscan",
            name="ai_tactics",
            field=models.JSONField(default=list),
        ),
        # Threat intelligence API results
        migrations.AddField(
            model_name="linkscan",
            name="virustotal_result",
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="linkscan",
            name="phishtank_result",
            field=models.JSONField(null=True, blank=True),
        ),
    ]
